# Generated by Django 3.0.8 on 2020-07-16 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
